site_name: George's Digital Garden
repo_name: LuciferUchiha/Digital-Garden
repo_url: https://github.com/LuciferUchiha/Digital-Garden
edit_uri: ""
theme:
  name: material
  features:
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: dark)" 
      scheme: my-dark
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: my-light
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LuciferUchiha
    - icon: fontawesome/solid/paper-plane
      link: mailto:rowla101@gmail.com

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - tables
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
