site_name: George's Digital Garden
repo_name: LuciferUchiha/Digital-Garden
repo_url: https://github.com/LuciferUchiha/Digital-Garden
edit_uri: ""
theme:
  name: material
  features:
    - navigation.top
  palette:
    scheme: slate
    primary: grey
    accent: grey
  custom_dir: 'custom/'

  
copyright: "Did my notes help you or did you enjoy one of my recipes? Then feel free to buy me a coffee :) ⇨ ⇨ ⇨"

extra:
  generator: false
  social:
    - icon: fontawesome/solid/coffee
      link: https://buymeacoffee.com/georgerowlands                
      name: Buy me a coffee
    - icon: fontawesome/brands/github
      link: https://github.com/LuciferUchiha
      name: Github link

plugins:
  - search
  - mkdocs-jupyter:
      include_source: True
  - mermaid2

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - tables
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
